name: Assign Inquiries

on:
  schedule:
    - cron: '0 22 * * *'  # 北京时间 6 点
    - cron: '0 1 * * *'    # 北京时间 9 点
    - cron: '0 4 * * *'    # 北京时间 12 点
    - cron: '0 7 * * *'    # 北京时间 15 点
    - cron: '0 10 * * *'   # 北京时间 18 点
    - cron: '0 12 * * *'   # 北京时间 20 点
  workflow_dispatch:  # 允许手动触发

jobs:
  run-script:
    runs-on: ubuntu-latest
    environment: LIFISHER_SECRETS  # 指定环境名称
    env:
      TZ: Asia/Shanghai  # 设置时区为北京时间 (UTC+8)
    steps:
      - uses: actions/checkout@v3  # 拉取代码

      - name: Set up R
        uses: r-lib/actions/setup-r@v2  # 安装 R

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libcurl4-openssl-dev libxml2-dev  # 安装 libcurl 和 libxml2 系统依赖

      - name: Cache R packages
        id: cache-r-packages
        uses: actions/cache@v3
        with:
          path: ~/.R/library  # R 依赖包的默认安装路径
          key: r-packages-${{ hashFiles('**/DESCRIPTION') }}  # 根据 DESCRIPTION 文件生成缓存键
          restore-keys: |
            r-packages-

      - name: Install R dependencies
        run: |
          Rscript -e 'install.packages(c("httr", "xml2", "jsonlite"), repos="https://cloud.r-project.org")'

      - name: Run script
        run: Rscript Assign-Inquiry.R  # 运行 R 脚本
        env:
          LIFISHER_CODES: ${{ secrets.LIFISHER_CODES }}
          LIFISHER_TOKEN: ${{ secrets.LIFISHER_TOKEN }}
          LIFISHER_VARIABLES: ${{ vars.LIFISHER_VARIABLES }}
          LIFISHER_STAFF_CODES: ${{ vars.LIFISHER_STAFF_CODES }}

      - name: Notify on success
        if: success()
        run: |
          echo "Script ran successfully!"

      - name: Notify on failure
        if: failure()
        run: |
          echo "Script failed!"
