name: Assign_Inquiries

on:
  workflow_dispatch:  # 允许手动触发

jobs:
  run-script:
    runs-on: ubuntu-latest
    environment: LIFISHER_SECRETS  # 指定环境名称
    env:
      TZ: Asia/Shanghai  # 设置时区为北京时间 (UTC+8)
    steps:
      - uses: actions/checkout@v3  # 拉取代码

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Run script
        run: python Assign_Inquiry.py  # 运行 Python 脚本
        env:
          LIFISHER_CODES: ${{ secrets.LIFISHER_CODES }}
          LIFISHER_TOKEN: ${{ secrets.LIFISHER_TOKEN }}
          LIFISHER_VARIABLES: ${{ vars.LIFISHER_VARIABLES }}
          LIFISHER_STAFF_CODES: ${{ vars.LIFISHER_STAFF_CODES }}

      - name: Notify on success
        if: success()
        run: |
          echo "Script ran successfully!"

      - name: Notify on failure
        if: failure()
        run: |
          echo "Script failed!"
