name: Reformat_Sheet

on:
  schedule:
    - cron: '20 22 * * *'  # 北京时间 6:10
    - cron: '20 1 * * *'   # 北京时间 9:10
    - cron: '20 4 * * *'   # 北京时间 12:10
    - cron: '20 7 * * *'   # 北京时间 15:10
    - cron: '20 10 * * *'  # 北京时间 18:10
    - cron: '20 12 * * *'  # 北京时间 20:10
  workflow_dispatch:

jobs:
  update-sheet:
    runs-on: ubuntu-latest
    environment: LIFISHER_SHEET_SECRETS  # Replace with your environment name

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Python dependencies
        run: |
          pip install gspread google-auth google-auth-oauthlib google-auth-httplib2 gspread-formatting

      - name: Create credentials file
        run: echo '${{ secrets.SHEET_KEY }}' > credentials.json

      - name: Run Python script
        env:
          SHEET_ID: ${{ vars.SHEET_ID }}
        run: python reFormat.py

      - name: Remove credentials file
        run: rm credentials.json
